### ISSUE TITLE
Hardcoded syscalls not available on my platform

### ISSUE THREAD

**Issue by diekmann** [teh/hsseccomp#1]
Hi,

I tried to compile hsseccomp 0.1.0.2 on Ubuntu 14.04.4 LTS, kernel 3.13.0. 

```
Building hsseccomp-0.1.0.2...
Preprocessing library hsseccomp-0.1.0.2...
In file included from dist/build/System/Linux/Seccomp_hsc_make.c:1:0:
Seccomp.hsc: In function ‘main’:
Seccomp.hsc:504:16: error: ‘__NR_cachectl’ undeclared (first use in this function)
/opt/ghc/7.10.3/lib/ghc-7.10.3/template-hsc.h:35:10: note: in definition of macro ‘hsc_const’
     if ((x) < 0)                                      \
          ^
Seccomp.hsc:504:16: note: each undeclared identifier is reported only once for each function it appears in
/opt/ghc/7.10.3/lib/ghc-7.10.3/template-hsc.h:35:10: note: in definition of macro ‘hsc_const’
     if ((x) < 0)                                      \
          ^
Seccomp.hsc:505:16: error: ‘__NR_cacheflush’ undeclared (first use in this function)
/opt/ghc/7.10.3/lib/ghc-7.10.3/template-hsc.h:35:10: note: in definition of macro ‘hsc_const’
     if ((x) < 0)                                      \
          ^
Seccomp.hsc:506:16: error: ‘__NR_sysmips’ undeclared (first use in this function)
/opt/ghc/7.10.3/lib/ghc-7.10.3/template-hsc.h:35:10: note: in definition of macro ‘hsc_const’
     if ((x) < 0)                                      \
          ^
Seccomp.hsc:507:16: error: ‘__NR_timerfd’ undeclared (first use in this function)
/opt/ghc/7.10.3/lib/ghc-7.10.3/template-hsc.h:35:10: note: in definition of macro ‘hsc_const’
     if ((x) < 0)                                      \
          ^
Seccomp.hsc:509:16: error: ‘__NR_getrandom’ undeclared (first use in this function)
/opt/ghc/7.10.3/lib/ghc-7.10.3/template-hsc.h:35:10: note: in definition of macro ‘hsc_const’
     if ((x) < 0)                                      \
          ^
Seccomp.hsc:510:16: error: ‘__NR_memfd_create’ undeclared (first use in this function)
/opt/ghc/7.10.3/lib/ghc-7.10.3/template-hsc.h:35:10: note: in definition of macro ‘hsc_const’
     if ((x) < 0)                                      \
          ^
Seccomp.hsc:511:16: error: ‘__NR_kexec_file_load’ undeclared (first use in this function)
/opt/ghc/7.10.3/lib/ghc-7.10.3/template-hsc.h:35:10: note: in definition of macro ‘hsc_const’
     if ((x) < 0)                                      \
          ^
Seccomp.hsc:513:16: error: ‘__NR_oldwait4’ undeclared (first use in this function)
/opt/ghc/7.10.3/lib/ghc-7.10.3/template-hsc.h:35:10: note: in definition of macro ‘hsc_const’
     if ((x) < 0)                                      \
          ^
Seccomp.hsc:549:16: error: ‘__NR_breakpoint’ undeclared (first use in this function)
/opt/ghc/7.10.3/lib/ghc-7.10.3/template-hsc.h:35:10: note: in definition of macro ‘hsc_const’
     if ((x) < 0)                                      \
          ^
Seccomp.hsc:550:16: error: ‘__NR_set_tls’ undeclared (first use in this function)
/opt/ghc/7.10.3/lib/ghc-7.10.3/template-hsc.h:35:10: note: in definition of macro ‘hsc_const’
     if ((x) < 0)                                      \
          ^
Seccomp.hsc:551:16: error: ‘__NR_usr26’ undeclared (first use in this function)
/opt/ghc/7.10.3/lib/ghc-7.10.3/template-hsc.h:35:10: note: in definition of macro ‘hsc_const’
     if ((x) < 0)                                      \
          ^
Seccomp.hsc:552:16: error: ‘__NR_usr32’ undeclared (first use in this function)
/opt/ghc/7.10.3/lib/ghc-7.10.3/template-hsc.h:35:10: note: in definition of macro ‘hsc_const’
     if ((x) < 0)                                      \
          ^
compiling dist/build/System/Linux/Seccomp_hsc_make.c failed (exit code 1)
command was: /usr/bin/gcc -c dist/build/System/Linux/Seccomp_hsc_make.c -o dist/build/System/Linux/Seccomp_hsc_make.o -fno-stack-protector -D__GLASGOW_HASKELL__=710 -Dlinux_BUILD_OS=1 -Dx86_64_BUILD_ARCH=1 -Dlinux_HOST_OS=1 -Dx86_64_HOST_ARCH=1 -Idist/build/autogen -include dist/build/autogen/cabal_macros.h -I/opt/ghc/7.10.3/lib/ghc-7.10.3/base_HQfYBxpPvuw8OunzQu6JGM/include -I/opt/ghc/7.10.3/lib/ghc-7.10.3/integ_2aU3IZNMF9a7mQ0OzsZ0dS/include -I/opt/ghc/7.10.3/lib/ghc-7.10.3/include -I/opt/ghc/7.10.3/lib/ghc-7.10.3/include/
```

If I remove the syscalls which are not available on my system (`cachectl`, `cacheflush`, `sysmips`, `timerfd`, `getrandom`, `memfd_create`, `kexec_file_load`, `oldwait4`), it compiles and the test suite passes.

The syscall numbers should not be hard coded.

**Comment by teh** [comment]
Ah, interesting. Thanks for the report.

I'm not sure whether conditional compilation is the right answer here, given that I build my binaries on a different kernel than I run in my production fleet. Same if you e.g. package for Debian, people might be running different kernels.

Maybe we could remove these calls for now and say the kernel (build time and run time) needs to >= 3.13?

Another option would be to distribute a newer kernel header and then fail at runtime when people try to whitelist calls not available on that kernel.

Any other ideas?

**Comment by diekmann** [comment]
Just removing these calls for now sounds okay. 

By the way, in the `SysCall` type definition, the comments (the syscall numbers) are very misleading. They can be different on every architecture. 
In the code, you are correctly using the `SCMP_SYS` macro to "Convert a syscall name into the associated syscall number" [cite: libseccomp], so there is no error here. 
To avoid confusion, I would still recommend to strip the hard-coded numbers in the comments ;-)

## 

Just one more thing, this may be highly off topic: Where are all the 'basic' system call definitions? 
For example I cannot find `exit`, `read`, `write`.

**Comment by diekmann** [comment]
Whups, I overlooked your latest commit. Thanks :+1:

**Comment by teh** [comment]
Some of these calls have been in linux for a long time. Is it possible that ubuntu doesn't e.g. compile with `kexec_file_load` ?

**Comment by teh** [comment]
Nevermind, this is a good source: http://manpages.ubuntu.com/manpages/wily/man2/syscalls.2.html

**Comment by teh** [comment]
seccomp only appeared in 3.17 so I guess we should assume 3.17 as our minimum version. Is that OK for you?

**Comment by teh** [comment]
(in that case we don't need to remove any syscalls):

```
                syscall  major  minor
98         getrandom(2)      3     17
131  kexec_file_load(2)      3     17
151     memfd_create(2)      3     17
257          seccomp(2)      3     17
```

**Comment by diekmann** [comment]
Ubuntu backported it to 3.13.0. I definitely don't have `getrandom`. Now you -- as upstream -- may decide: conditional compilation or requiring kernel >= 3.17 or backwards compatibility which lacks important syscalls?

**Comment by teh** [comment]
If this works for you I'll release a new version to hackage.

**Comment by diekmann** [comment]
Let's do some more testing before releasing a new hackage version. I hope I can integrate hsseccomp to my application soon.

**Comment by teh** [comment]
@diekmann ping this bug when you want me to release to hackage - my code still works so I'm good any time

**Comment by diekmann** [comment]
@teh ping

**Comment by teh** [comment]
It's here: https://hackage.haskell.org/package/hsseccomp-0.2.0.1

I added you as an author, I hope that's OK because your info is publicly available. Let me know if you prefer not to be on the package.

**Comment by diekmann** [comment]
Thanks, that's cool :-)
