### ISSUE TITLE
Test Suite: killOnAnyOpen

### ISSUE THREAD

**Issue by diekmann** [teh/hsseccomp#2]
Hi,

What was the intention behind the `killOnAnyOpen` test case? The default behavior is set to kill anything (`S.seccomp_init S.SCMP_ACT_KILL`). But opening is explicitly allowed (`S.seccomp_rule_add_array ctx S.SCMP_ACT_ALLOW S.SCopen []`). Regarding the name, shouldn't the `KILL` and the `ALLOW` be swapped? The test suite is still passing. It is also passing if I swap `KILL` and `ALLOW`. Something seems odd with the test setup?

By the way, I tried to do some printf debugging, where is the `write` syscall?

**Comment by teh** [comment]
I think the test exposes a bug. It shouldn't terminate. The logs make it look like the kill is happening because of syscall 228 which is `clock_gettime`. 

```
Apr 26 10:43:24 zap audit[23056]: SECCOMP auid=1000 uid=1000 gid=1000 ses=1 pid=23056 comm="seccomp-test" exe="/home/tom/devel/hsseccomp/dist/build/seccomp-test/seccomp-test" sig=31 arch=c000003e syscall=228 compat=0 ip=0x7ffc46deabdf code=0x0
```

I whitelisted that call and repeated until the process wasn't killed any more, arriving at this list:

```
    _ <- S.seccomp_rule_add_array ctx S.SCMP_ACT_ALLOW S.SCclock_gettime []
    _ <- S.seccomp_rule_add_array ctx S.SCMP_ACT_ALLOW S.SCrt_sigprocmask []
    _ <- S.seccomp_rule_add_array ctx S.SCMP_ACT_ALLOW S.SCrt_sigaction []
    _ <- S.seccomp_rule_add_array ctx S.SCMP_ACT_ALLOW S.SCtimer_settime []
    _ <- S.seccomp_rule_add_array ctx S.SCMP_ACT_ALLOW S.SCtimer_delete []
    _ <- S.seccomp_rule_add_array ctx S.SCMP_ACT_ALLOW S.SCexit_group []
    _ <- S.seccomp_rule_add_array ctx S.SCMP_ACT_ALLOW S.SCselect []
    _ <- S.seccomp_rule_add_array ctx S.SCMP_ACT_ALLOW S.SCshmctl []
    _ <- S.seccomp_rule_add_array ctx S.SCMP_ACT_ALLOW S.SCwrite []
    _ <- S.seccomp_rule_add_array ctx S.SCMP_ACT_ALLOW S.SCprctl []
```

Not sure that whitelisting all those is great, but it's required to make the Haskell runtime work.

**Comment by teh** [comment]
As you can probably tell by the missing write `syscall` I'm using seccomp in a weird context so I appreciate someone using it for new things, thanks!

**Comment by diekmann** [comment]
I'm trying to write some more test cases and preparing a pull request for you.

https://github.com/diekmann/hsseccomp

Unfortunately, my `allowStdOutKillStdErr` test always fails. Do you have any reference test for `S.SCMP_ACT_ERRNO`?
