### ISSUE TITLE
More test cases

### ISSUE THREAD

**Issue by diekmann** [teh/hsseccomp#3]
I'm trying to write some more test cases and preparing a pull request for you.

https://github.com/diekmann/hsseccomp

Unfortunately, my `allowStdOutKillStdErr` test always fails. Do you have any reference test for `S.SCMP_ACT_ERRNO`?

**Comment by diekmann** [comment]
Okay, I figured out how to get it working, but it is kind of ugly. Do you have a better idea (without exceptions)?

By the way, do you think `whitelistHaskellRuntimeCalls` should be part of the main library? But this functions needs to be further tested and improved.

**Comment by teh** [comment]
Neat.

I don't think there's a better way than catching the exception unless you avoid `System.IO` and use the FFI to directly call c functions.

re `whitelistHaskellRuntimeCalls` - maybe, as you said I haven't tested it extensively so maybe move it and stick a  "WARNING This function is new and untested" into the doc string?

**Comment by teh** [comment]
Closing since you found a solution. Ta.
